######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 8 12:00:21 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 02push.cpp
