######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 9 11:52:15 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += login.h
FORMS += login.ui
SOURCES += main.cpp
