######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 9 09:37:06 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += slid.h
SOURCES += main.cpp slid.cpp
