######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 8 10:31:58 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
