######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 8 17:24:53 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += emitsignal.h
SOURCES += emit.cpp emitsignal.cpp
