######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 14 09:03:02 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
