######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 8 14:32:12 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . 01helloworld 02push
INCLUDEPATH += .

# Input
SOURCES += widget.cpp 01helloworld/hello.cpp 02push/02push.cpp
