######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 8 14:35:27 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += widget.cpp
