######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 9 10:30:48 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += calc.h
SOURCES += calc.cpp main.cpp
