######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 10 14:21:21 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydraw.h
