######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 12 10:50:36 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
