######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 8 14:47:10 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qq.cpp
